first_project/first_app/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

app_name = 'first_app'

'''urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other')
]'''
urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/',views.user_login, name='user_login')
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    #path('users/', views.users, name='users'),
    path('first_app/', include('first_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/', views.special, name='special'),
]
 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name
    
class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name
    
class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)
    
'''class User(models.Model):
    first_name = models.CharField(max_length=264)
    last_name = models.CharField(max_length=264)
    email = models.EmailField(max_length=264)

    def __str__(self):
        return self.first_name + ' ' + self.last_name'''
    

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.core import validators
#from .models import User
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

'''def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError('Needs to start with z')

class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, 
                                 widget = forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])
    def clean_botcatcher(self):
        botcatcher = self.cleaned_data['botcatcher']
        if len(botcatcher) > 0:
            raise forms.ValidationError('GOTCHA BOT!')
        return botcatcher
    
    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError('Make sure emails match')'''

'''class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__' '''


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')
    
    

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Webpage, AccessRecord, Topic, User
#from first_app.forms import NewUserForm

from . import forms

from first_app.forms import UserForm, UserProfileInfoForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def index(request):
    '''webpages_list  = AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpages_list}

    my_dict = {'insert_me':'Hello I am from views.py'}
    return render(request, 'first_app/index.html',context=date_dict)'''
    #context_dict = {'text':'hello world', 'number':100}
    return render(request, 'first_app/index.html')


'''def users(request):
    users_list = User.objects.order_by('first_name')
    user_dict = {'access_records':users_list}
    return render(request, 'first_app/users.html', context=user_dict)
   form = NewUserForm()
   if request.method == 'POST':
       form = NewUserForm(request.POST)

       if form.is_valid():
           form.save(commit=True)
           return index(request)
       else:
           print('ERROR FORM INVALID')

   return render(request, 'first_app/users.html', {'form':form})'''

@login_required
def special(request):
    return HttpResponse('You are logged in, Nice')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)
        if form.is_valid():
            print('VALIDATION SUCCESS')
            print('Name: ',form.cleaned_data['name'])
            print('Email: ',form.cleaned_data['email'])
            print('Text: ',form.cleaned_data['text'])




    return render(request, 'first_app/form_page.html', {'form':form})

def other(request):
    return render(request, 'first_app/other.html')

def relative(request):
    return render(request, 'first_app/relative_url_templates.html')


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'first_app/registration.html', {'user_form':user_form,
                                                           'profile_form':profile_form,
                                                           'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('Someone tried to login and failer!')
            print('Username: {} and password {}'.format(username,password))
            return HttpResponse('Invalid login details supplied')
    return render(request, 'first_app/login.html', {})

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>

    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{%url 'index'%}">Home</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'first_app:register' %}">Register</a></li>

                    {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>

                    {% else %}
                    <li><a class="navbar-link" href="{% url 'first_app:user_login' %}">Login</a></li>

                    {% endif %}
                </ul>
            </div>

        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
        

    </body>
</html> 

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Users</title>
        <!-- <link rel="stylesheet" href="{% static "css/mystyle.css" %}"> -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <form method="POST">
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" name = "" class = "btn btn-primrary" value="Submit">
            </form>
        </div>

    </body>

</html>

first_project/templates/first_app/index.html
{% extends "first_app/base.html" %}
{% block body_block %}

<div class="container">
    <h1>Django level Five</h1>
</div>
{% endblock %}

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'first_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter username">
         
        <label for="password">Password</label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>

</div>

{% endblock %}

first_project/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>Welcome to Other!</h1>
<h2>This is an example of template inheritance</h2>
{% endblock %}

first_project/templates/first_app/registration.html
{% extends "first_app/base.html" %}
{% load static %}
{% block body_block %}

<div class="container">
    {% if registered %}
    <h1>Thank you for registering</h1>
    {% else %}
    <h1>Register here!</h1>
    <h1>Fill out the form</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">

    </form>

    {% endif %}
</div>
{% endblock %}

first_project/templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Django Page</title>
    </head>
    <body>
        <h1>WELCOME to relative url templates</h1>

        <a href="{% url 'first_app:other' %}">Other</a>
        <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
        <a href="{% url 'index' %}">Link to index</a>


    </body>

</html>

first_project/templates/first_app/users.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Users</title>
        <!-- <link rel="stylesheet" href="{% static "css/mystyle.css" %}"> -->
    </head>
    <body>
        <h1>Please sign up here</h1>

        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="submit">
        </form>


        <!--<h1>Here are your users</h1>

        <ol>
            {% for acc in access_records %}
            <li>User Info</li>
            <ul>
                <li>First Name: {{ acc.first_name }}</li>
                <li>Last Name: {{ acc.last_name }}</li>
                <li>Email: {{ acc.email }}</li>
            </ul>
            {% endfor %}
        </ol> -->

        <!-- <h1>Hi this is a picture of Django</h1>

        <h2>Here are your access records:</h2>

        <div class="djangtwo">
        {% if access_records %}
        <table>
            <thead>
                <th>Site Name</th>
                <th>Date Accessed</th>
            </thead>
            {% for acc in access_records %}
            <tr>
                <td>{{ acc.name }}</td>
                <td>{{ acc.date }}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>No access records</p>
        {% endif %}
        </div>
        <br>
        <img src="{% static "images/pic.png" %}" alt="Uh oh!"> -->

    </body>

</html>